#!/bin/sh
cd `dirname $0`/..

mkdir -p build_android_armeabi_v7a_hard_opencl
cd build_android_armeabi_v7a_hard_opencl

cmake -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON -DCMAKE_TOOLCHAIN_FILE=../android/android.toolchain.cmake \
	-DANDROID_ABI="armeabi-v7a-hard with NEON" -DANDROID_NATIVE_API_LEVEL=21 \
	-DENABLE_NEON=ON -DENABLE_VFPV3=ON \
	-DWITH_VA=OFF -DWITH_VA_INTEL=OFF \
	-DWITH_TBB=ON -DBUILD_TBB=ON -DWITH_OPENCL=ON -DWITH_OPENGL=OFF \
	-DBUILD_CUDA_STUBS=OFF -DWITH_CUDA=OFF -DWITH_CUFFT=OFF -DWITH_CUBLAS=OFF -DWITH_NVCUVID=OFF -DHAVE_CUDA=0 \
	-DWITH_EIGEN=OFF \
	-DWITH_JASPER=OFF -DWITH_WEBP=OFF -DWITH_JPEG=OFF \
	-DWITH_OPENEXR=OFF -DWITH_PNG=OFF -DWITH_TIFF=OFF \
	-DBUILD_WITH_DEBUG_INFO=OFF \
	-DBUILD_TIFF=OFF -DBUILD_JASPER=OFF -DBUILD_JPEG=OFF -DBUILD_PNG=OFF \
	-DENABLE_FAST_MATH=ON \
	-DENABLE_NOISY_WARNINGS=ON \
	-DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF \
	-DINSTALL_PYTHON_EXAMPLES=OFF -DBUILD_ANDROID_EXAMPLES=OFF -DBUILD_DOCS=OFF -DBUILD_CUDA_STUBS=OFF -DINSTALL_ANDROID_EXAMPLES=OFF -DINSTALL_PYTHON_EXAMPLES=OFF \
	-DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DINSTALL_TESTS=OFF \
	$@ ../..
